spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (??: none, create, create-drop, update, validate)
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
          generate_statistics: true
        format_sql: true  # SQL ??? ??
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false  # ??? SQL ?? ??
    
kakao:
  key:
  url: https://dapi.kakao.com/v3/search/book
naver:
  client-id:
  client-secret:
  book-search-url: https://openapi.naver.com/v1/search/book.json
